RTP velocity representation
cp2k/cp2k pull request #722
Opened 2020-01-10 14:11 UTC by mattiatj

Include expectation value calculation of
- electric dipole moment
- electric quadrupole moment
in their velocity representation for RTP.

In the presence of pseudo potentials additional commutator terms are included for
- the velocity representation of the electric dipole moment
- the velocity representation of the electric quadrupole moment
- the magnetic dipole moment.

The input includes in DFT%PRINT%MOMENTS new keywords
- VEL_REPRS to switch on velocity representations
- COM_NL to include the commutator terms

additionally a second reference point can be included via the keywords
- SECOND_REFERENCE_POINT (logical)
- REF_2 (COM, COAC, ZERO, USER_DEFINED)
- REF_POINT_2 (x y z)

In DFT%REAL_TIME_PROPAGATION the new keyword
- COM_NL to include the commutator term for a delta pulse in the velocity representation
was added.

2020-01-10 14:44 UTC, dev-zero requested changes
The code in `commutator_rpnl.F` seems to be inspired from an earlier version of `core_ppnl.F` without the refactoring done in 63f2e15396cd4d5323c594035dca6ba31437099f .
If not already done I'd suggest looking over the changes in the mentioned commit and check whether they apply to your code as well.

2020-01-10 14:44 UTC, dev-zero commented on src/commutator_rpnl.F
> +      TYPE(qs_kind_type), DIMENSION(:), POINTER          :: qs_kind_set
`INTENT(...)` missing. I know you probably took some other routine as an example, but could you please add appropriate `INTENT(IN/OUT/INOUT)`?

2020-01-10 14:44 UTC, dev-zero commented on src/commutator_rpnl.F
> +!> \brief ...
please add some description

2020-01-10 14:44 UTC, dev-zero commented on src/commutator_rpnl.F
> +      IF (.NOT. (my_rv .OR. my_rxrv .OR. my_rrv)) RETURN
in this case you'll be missing the corresponding `timestop`. Are you sure this isn't rather a case for a `CPABORT` (e.g. misuse of the function by a developer)?

2020-01-10 14:44 UTC, dev-zero commented on src/commutator_rpnl.F
> +      IF (ppnl_present) THEN
since you already have early exits I'd also use the same pattern here and do `IF (.NOT. ppnl_present) RETURN`

2020-01-10 14:44 UTC, dev-zero commented on src/commutator_rpnl.F
> +            CPASSERT(PRESENT(ref_point))
I'd shift this precondition check up to the others (together with the one further down below). And possible add some comment behind the `CPASSERT`s.

2020-01-10 14:44 UTC, dev-zero commented on src/commutator_rpnl.F
> +               CPABORT('PPNL unknown')
you'll never end up here, right?

2020-01-10 14:44 UTC, dev-zero commented on src/commutator_rpnl.F
> +      TYPE(block_p_type), DIMENSION(:), POINTER          :: blocks_rrv, blocks_rv, blocks_rxrv
I think it should be possible to use `ALLOCATABLE` here instead of `POINTER`, might be true for others as well

2020-01-10 14:44 UTC, dev-zero commented on src/input_cp2k_dft.F
> +                          description="Calculate expectation values the el. multipole moments in their velocity"// &
`of` missing?

2020-01-10 14:44 UTC, dev-zero commented on src/qs_moments.F
> +         dab = SQRT(rab2)
use `NORM2` here and drop `rab2`?

2020-01-10 14:44 UTC, dev-zero commented on src/qs_moments.F
> +         ! trace = 0._dp
dead code?

2020-01-10 14:46 UTC, dev-zero commented
the error can likely be fixed by `mmom(:) = mmom + nlcom_rxrv` (or more `:` depending on rank)

2020-01-10 16:14 UTC, mattiatj commented
Thanks! I will look at the openMP next week.

2020-01-14 16:32 UTC, mattiatj commented
- I adapted the calculation of integrals from core_ppnl into a separate routine in sap_kind_types.F which can be used by both the routines in core_ppnl and commutator_rpnl
- I rewrote the construction of the commutators with MATMUL instead of dgem

2020-02-24 15:10 UTC, dev-zero approved these changes

2020-02-24 15:11 UTC, merged