KG contribution to Harris functional forces
cp2k/cp2k pull request #739
Opened 2020-01-17 15:07 UTC by fbelle

Adding Kim-Gordon subsystem DFT support (KG_METHOD ATOM and EMBEDDING) for Harris functional energy correction force calculations

*Prettify

2020-01-17 16:00 UTC, dev-zero requested changes
other than commented lines LGTM

2020-01-17 16:01 UTC, dev-zero commented on src/kg_correction.F
> +!> \param
interesting that `doxify` doesn't remove those lines

2020-01-17 16:02 UTC, dev-zero commented on src/kg_correction.F
> +      logger => cp_get_default_logger()
not used, or did I miss it?

2020-01-22 09:38 UTC, fbelle commented on src/kg_correction.F
> +      TYPE(qs_environment_type), POINTER                 :: qs_env
Renamed to create_kernel to avoid confusion. Added description about allocation of vxc.

2020-01-22 09:48 UTC, merged

2020-01-22 09:48 UTC, dev-zero commented
you still might want to add a regtest for this at some point

2020-01-22 09:55 UTC, fbelle commented
Thank you! Adding a regtest is indeed on my to do list!